### PR TITLE
Moved purely Address and Entry tests to dedicated test classes.

### PR DESCRIPTION
**Pull request by ndobromirov**
This is attempt at point 1 from issue #43.

### CODE REVIEW

**Comment by davidstrauss** [comment]
The test failures are for style issues in the code. I'm happy to fix them if you'd find it tedious.

**Comment by ndobromirov** [comment]
Well I am using NetBeans, and for some reason it is not respecting the .editorconfig file (or it needs to be extended to format braces also).
I'll fix it and make a new pull request.

**Comment by ndobromirov** [comment]
Strange, the build breaks, even if the tests pass.

**Comment by davidstrauss** [comment]
The tests aren't necessarily passing. `phpunit` is segfaulting PHP.

**Comment by danielbachhuber** [comment]
> The tests aren't necessarily passing. `phpunit` is segfaulting PHP.

It's an APCu update: https://bugs.php.net/bug.php?id=73286

**Comment by greg-1-anderson** [comment]
The build has been fixed on the master branch; rebase this PR and the tests should pass.

**Pull request merged**
