### PR TITLE
Duplicate Bug Fix

### PR DESCRIPTION
**Pull request by ellisonpatterson**
### Overview
This pull request:

- [x] Fixes a bug
- [x] Minor enhancement

### Summary
Double quotes in queries were causing issues. Changed to graves. Also solves the duplicate entry bug for me which is great!

When pruning I made it check if the first index exists as it would sometimes think the deletion pattern was empty when it wasn't.

I have also made the `queueDeletion` method public as using instead of a direct delete is probably more optimal but not 100% certain.

### Description
n/a

### CODE REVIEW

**Comment by davidstrauss** [comment]
Your connection needs different configuration for LCache. Specifically, if you're using MySQL or MariaDB, you will need to add the necessary options to be more ANSI compliant. You can see the connection setup for the Drupal and WordPress modules for some examples.

In case you're wondering, the double quotes allow unit testing on SQLite and production with MySQL.

**Comment by ellisonpatterson** [comment]
What steps could be taken to increase compatibility across the various setups as things were not working properly for me when the double quotes were used.

**Comment by davidstrauss** [comment]
It looks like you changed the condition at the beginning on the cleanup, too. I will see if there's an issue there.

**Comment by ellisonpatterson** [comment]
For some reason it was skipping some entries with only a single entry in the array. I'm not sure if `empty()` is quirky like this.

**Comment by davidstrauss** [comment]
> What steps could be taken to increase compatibility across the various setups as things were not working properly for me when the double quotes were used.

The right options for MySQL to use ANSI quotes are visible here:

https://github.com/lcache/drupal-7/blob/master/lcache.cache.inc

**Comment by ellisonpatterson** [comment]
Ah that would explain it then. I'm not sure it would be great to set that though as I'm worried it might break my application since it's not using that. I'm not initializing a new connection to the DB but using the existing one to limit new connections. Would that sort of scenario make integrating into new applications a strain?

**Comment by davidstrauss** [comment]
You should really use a different PDO handle for LCache. It would not be good to have it share transactions with your main app.

**Comment by davidstrauss** [comment]
Really, the only alternative to using ANSI quotes is carefully avoiding reserved words for the schema in every targeted DB system. I'm open to that idea, but, given the good reasons for using a separate connection, I'm not sure it would help much. The settings on the LCache PDO connection won't affect the main application's connection.

**Comment by ellisonpatterson** [comment]
Alright I will separate them out :)

**Pull request closed without merging**
